import { BadRequestException, ConflictException, Injectable, UnauthorizedException } from '@nestjs/common';
import { AuditAction, User } from '@prisma/client';
import { JwtService } from '@nestjs/jwt';
import * as bcrypt from 'bcrypt';
import { createHash, randomBytes } from 'crypto';
import { Request } from 'express';
import { PrismaService } from '../prisma/prisma.service';
import { LoginDto, RegisterDto, ResetPasswordDto } from './dto';

const hash = (value: string) => createHash('sha256').update(value).digest('hex');
const safeUser = (u: User) => ({ id: u.id, email: u.email, fullName: u.fullName, role: u.role, isEmailVerified: u.isEmailVerified, lastLoginAt: u.lastLoginAt });
@Injectable() export class AuthService {
  constructor(private prisma: PrismaService, private jwt: JwtService) {}
  private meta(req: Request) { return { ipAddress: req.ip, userAgent: req.get('user-agent') }; }
  private async audit(action: AuditAction, userId?: string, metadata?: object) { await this.prisma.auditLog.create({ data: { action, userId, metadata } }); }
  private async tokens(user: User) { const payload = { sub: user.id, email: user.email, role: user.role }; const accessToken = await this.jwt.signAsync(payload, { secret: process.env.JWT_ACCESS_SECRET, expiresIn: '15m' }); const refreshToken = await this.jwt.signAsync(payload, { secret: process.env.JWT_REFRESH_SECRET, expiresIn: '7d' }); await this.prisma.refreshToken.create({ data: { userId: user.id, tokenHash: hash(refreshToken), expiresAt: new Date(Date.now() + 7 * 86400000) } }); return { accessToken, refreshToken, user: safeUser(user) }; }
  async register(dto: RegisterDto, req: Request) { const email = dto.email.toLowerCase(); if (await this.prisma.user.findUnique({ where: { email } })) throw new ConflictException('An account with this email already exists'); const user = await this.prisma.user.create({ data: { email, fullName: dto.fullName, passwordHash: await bcrypt.hash(dto.password, 12) } }); const token = randomBytes(32).toString('hex'); await this.prisma.verificationToken.create({ data: { userId: user.id, tokenHash: hash(token), expiresAt: new Date(Date.now() + 86400000) } }); await this.audit(AuditAction.REGISTER, user.id, this.meta(req)); return { message: 'Account created. Please verify your email.', developmentVerificationUrl: `${process.env.WEB_URL ?? 'http://localhost:4200'}/verify-email?token=${token}` }; }
  async login(dto: LoginDto, req: Request) { const user = await this.prisma.user.findUnique({ where: { email: dto.email.toLowerCase() } }); const valid = !!user && await bcrypt.compare(dto.password, user.passwordHash); if (!valid) { if (user) await this.prisma.loginHistory.create({ data: { userId: user.id, succeeded: false, ...this.meta(req) } }); throw new UnauthorizedException('Email or password is incorrect'); } if (!user.isEmailVerified) throw new UnauthorizedException('Please verify your email first'); await this.prisma.user.update({ where: { id: user.id }, data: { lastLoginAt: new Date() } }); await this.prisma.loginHistory.create({ data: { userId: user.id, succeeded: true, ...this.meta(req) } }); await this.audit(AuditAction.LOGIN, user.id, this.meta(req)); return this.tokens(user); }
  async refresh(raw: string) { try { const payload = await this.jwt.verifyAsync(raw, { secret: process.env.JWT_REFRESH_SECRET }); const record = await this.prisma.refreshToken.findUnique({ where: { tokenHash: hash(raw) }, include: { user: true } }); if (!record || record.revokedAt || record.expiresAt < new Date()) throw new Error(); await this.prisma.refreshToken.update({ where: { id: record.id }, data: { revokedAt: new Date() } }); await this.audit(AuditAction.REFRESH_TOKEN, record.userId); return this.tokens(record.user); } catch { throw new UnauthorizedException('Invalid or expired refresh token'); } }
  async logout(raw: string) { await this.prisma.refreshToken.updateMany({ where: { tokenHash: hash(raw), revokedAt: null }, data: { revokedAt: new Date() } }); }
  async forgotPassword(email: string) { const user = await this.prisma.user.findUnique({ where: { email: email.toLowerCase() } }); if (!user) return { message: 'If that account exists, a reset link has been sent.' }; const token = randomBytes(32).toString('hex'); await this.prisma.passwordResetToken.create({ data: { userId: user.id, tokenHash: hash(token), expiresAt: new Date(Date.now() + 3600000) } }); await this.audit(AuditAction.PASSWORD_RESET_REQUEST, user.id); return { message: 'If that account exists, a reset link has been sent.', developmentResetUrl: `${process.env.WEB_URL ?? 'http://localhost:4200'}/reset-password?token=${token}` }; }
  async resetPassword(dto: ResetPasswordDto) { const record = await this.prisma.passwordResetToken.findFirst({ where: { tokenHash: hash(dto.token), usedAt: null, expiresAt: { gt: new Date() } } }); if (!record) throw new BadRequestException('Reset link is invalid or expired'); await this.prisma.$transaction([this.prisma.user.update({ where: { id: record.userId }, data: { passwordHash: await bcrypt.hash(dto.password, 12) } }), this.prisma.passwordResetToken.update({ where: { id: record.id }, data: { usedAt: new Date() } }), this.prisma.refreshToken.updateMany({ where: { userId: record.userId, revokedAt: null }, data: { revokedAt: new Date() } })]); await this.audit(AuditAction.PASSWORD_RESET, record.userId); }
  async verifyEmail(token: string) { const record = await this.prisma.verificationToken.findFirst({ where: { tokenHash: hash(token), usedAt: null, expiresAt: { gt: new Date() } } }); if (!record) throw new BadRequestException('Verification link is invalid or expired'); await this.prisma.$transaction([this.prisma.user.update({ where: { id: record.userId }, data: { isEmailVerified: true } }), this.prisma.verificationToken.update({ where: { id: record.id }, data: { usedAt: new Date() } })]); await this.audit(AuditAction.EMAIL_VERIFIED, record.userId); return { message: 'Email verified. You can now sign in.' }; }
  async me(id: string) { const user = await this.prisma.user.findUniqueOrThrow({ where: { id } }); return safeUser(user); }
  async loginHistory(id: string) { return this.prisma.loginHistory.findMany({ where: { userId: id }, orderBy: { createdAt: 'desc' }, take: 20 }); }
}
